version: '3.8'
services:
  prefect-server:
    image: prefecthq/prefect:3.6.7-python3.11
    container_name: prefect-server
    command: prefect server start
    ports:
      - "4200:4200"
    environment:
      - PREFECT_API_SERVICES_UI_ENABLED=true
      - PREFECT_UI_API_URL=http://localhost:4200/api
      - PREFECT_SERVER_API_HOST=0.0.0.0
      - PREFECT_API_DATABASE_CONNECTION_URL=postgresql+asyncpg://prefect:prefect@postgres:5432/prefect
    depends_on:
      - postgres

  postgres:
    image: postgres:14
    container_name: prefect-postgres
    environment:
      - POSTGRES_DB=prefect
      - POSTGRES_USER=prefect
      - POSTGRES_PASSWORD=prefect

    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"



volumes:
  postgres_data: